embed_assets: on

javascripts:
  screen:
    - public/javascripts/vendor/jquery-1.5.1.js
    - public/javascripts/vendor/jquery-ui-1.8.13.custom.js
    - public/javascripts/application.js
    - public/javascripts/rails.js

stylesheets:
  screen:
    - public/stylesheets/fancybox/jquery.fancybox-1.3.4.css
    - public/stylesheets/compiled/screen.css
